const categories = {
  
    Accessories: [
      {
        id: 1,
        title: "Bookish Dril Baseball Cap",
        price: 445,
        descripton: 'Your everyday baseball cap, simple but elegant.',
        category: "Hats",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691626787/Garments/BlueBalenciagaCap.jpg?_s=public-apps",
        occasions: "Casual", 
        brand: "Balenciaga",
        color: "Blue",
      },
       {
        id: 2,
        title: "Oversized Shield Sunglasses",
        price: 1839,
        descripton: 'Stainless steel and Nylon 100%, perfect for the Summer season.',
        category: "Sunglasses",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691628278/Garments/GreenRickOwensSunglasses.jpg?_s=public-apps",
        occasions: "Formal",
        brand: "Rick Owens",
        color: "Green",
      },
       {
        id: 3,
        title: "Adjustable Adult Baseball Belt",
        price: 34.57,
        descripton: 'Tech Essentials Reversible Belt, athletic weave that prioritizes comfort.',
        category: "Belts",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691629469/Garments/NavyBlueBeltNikeBelt.jpg?_s=public-apps",
        occasions: "Athleisure",
        brand: "Nike",
        color: "Dark Blue",
      },
      {
        id: 4,
        title: "Logo Print Socks",
        price: 93.95,
        descripton: 'Stretch design by Stella McCartney. Unlock true performance with style.',
        category: "Socks",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691630275/Garments/OrangeAdidasSocks.jpg?_s=public-apps",
        occasions: "Athleisure",
        brand: "Adidas",
        color: "Orange",
      }
    ]
  ,

      Bags: [
   {
        id: 1,
        title: "EDC Backpack",
        price: 35.20,
        descripton: 'The perfect casual/skating backpack for all of your essentials. Padded layers for extra protection.',
        category: "Backpacks",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691631643/Garments/GreenConverseBackpack.jpg?_s=public-apps",
        occasions: "Casual", 
        brand: "Converse",
        color: "Green",
      },
       {
        id: 2,
        title: "Explorer Denim Belt Bag",
        price: 1090,
        descripton: 'Washed denim bag with zip. Stand out in the streets with the classic Balenciaga logo.',
        category: "Fanny Packs",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691632357/Garments/BlueBalenciagaFannyPack.jpg?_s=public-apps",
        occasions: "Casual",
        brand: "Balenciaga",
        color: "Blue",
      },
       {
        id: 3,
        title: "Navy Nylon Bag",
        price: 995,
        descripton: 'Break a sweat with class using this athletic crafted bag featuring the classic logo pattern.',
        category: "Duffel Bags",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691638822/Garments/DarkBlueOffWhiteDuffle.jpg?_s=public-apps",
        occasions: "Athleisure",
        brand: "Off-White",
        color: "Dark Blue",
      }
      ],

      Clothing:[
      {
        id: 1,
        title: "Mercantile Mens Classic Fit Oxford",
        price: 80.27,
        descripton: `Maximum comfort and style await with the Oxford shirt's microfibers tailored to suit your needs.`,
        category: "Shirts",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691640302/Garments/GreenJ.CrewShirt.jpg?_s=public-apps",
        occasions: "Formal", 
        brand: "J.Crew",
        color: "Green",
      },
       {
        id: 2,
        title: "Level T Cotton T-Shirt",
        price: 135.33,
        descripton: 'Crewneck Tee meeting your essential needs, made with premium cotton pullover style.',
        category: "T-Shirts",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691639749/Garments/OrangeRickOwensTShirt.jpg?_s=public-apps",
        occasions: "Casual",
        brand: "Rick Owens",
        color: "Orange",
      },
       {
        id: 3,
        title: "Universal Winter Mens Jacket",
        price: 335.49,
        descripton: 'Arctic tested jacket, perfect for your winter wardrobe.',
        category: "Outerwear",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691640667/Garments/DarkBlueConverseOuterwear.jpg?_s=public-apps",
        occasions: "Casual",
        brand: "Converse",
        color: "Dark Blue",
      },
      {
        id: 4,
        title: "Oversized Suit Trousers",
        price: 1181,
        descripton: 'Altered to an oversized fit, lunge with ease with this stylish bottom.',
        category: "Trousers",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691641072/Garments/BlueOff-WhiteTrousers.jpg?_s=public-apps",
        occasions: "Formal", 
        brand: "Off-white",
        color: "Blue",
      },
      {
        id: 5,
        title: "Sportswear Dance Cargo Pants",
        price: 62.99,
        descripton: 'Definitely stand out with these athletic bottoms with a 3D Classic Swoosh',
        category: "Jeans",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691641560/Garments/OrangeNikeJeans.jpg?_s=public-apps",
        occasions: "Athleisure",
        brand: "Nike",
        color: "Orange",
      },
      {
        id: 6,
        title: "Trefoil Essential Shorts",
        price: 60,
        descripton: 'Easy to wear drawcord waist shorts that promises comfort.',
        category: "Shorts",
        image: "https://res.cloudinary.com/dmhnsp8sj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1691641963/Garments/GreenAdidasShorts.jpg?_s=public-apps",
        occasions: "Athleisure",
        brand: "Adidas",
        color: "Green",
      }
      ]

    };


    export default categories;
