const categories = {
  
    Accessories: [
      {
        id: 1,
        title: "Bookish Dril Baseball Cap",
        price: 445,
        descripton: 'Your everyday baseball cap, simple but elegant.',
        category: "Hats",
        image: "https://asset.cloudinary.com/dmhnsp8sj/c63a95974a33bbc4e2a11343abcced76",
        occasions: "Casual", 
        brand: "Balenciaga",
        color: "Blue",
      },
       {
        id: 2,
        title: "Oversized Shield Sunglasses",
        price: 1839,
        descripton: 'Stainless steel and Nylon 100%, perfect for the Summer season.',
        category: "Sunglasses",
        image: "https://asset.cloudinary.com/dmhnsp8sj/7b47c68c36f836e2271a96ebbc38d89f",
        occasions: "Formal",
        brand: "Rick Owens",
        color: "Green",
      },
       {
        id: 3,
        title: "Adjustable Adult Baseball Belt",
        price: 34.57,
        descripton: 'Tech Essentials Reversible Belt, athletic weave that prioritizes comfort.',
        category: "Belts",
        image: "https://asset.cloudinary.com/dmhnsp8sj/7d9d4f1970b3d56911e13636d5ece90d",
        occasions: "Athleisure",
        brand: "Nike",
        color: "Dark Blue",
      },
      {
        id: 4,
        title: "Logo Print Socks",
        price: 93.95,
        descripton: 'Stretch design by Stella McCartney. Unlock true performance with style.',
        category: "Socks",
        image: "https://asset.cloudinary.com/dmhnsp8sj/76288a3c942332603fe0eb31024fa7da",
        occasions: "Athleisure",
        brand: "Adidas",
        color: "Orange",
      }
    ]
  ,

      Bags: [
   {
        id: 1,
        title: "EDC Backpack",
        price: 35.20,
        descripton: 'The perfect casual/skating backpack for all of your essentials. Padded layers for extra protection.',
        category: "Backpacks",
        image: "https://asset.cloudinary.com/dmhnsp8sj/63296dac85877a0bc7d59074b5f7bcb1",
        occasions: "Casual", 
        brand: "Converse",
        color: "Green",
      },
       {
        id: 2,
        title: "Explorer Denim Belt Bag",
        price: 1090,
        descripton: 'Washed denim bag with zip. Stand out in the streets with the classic Balenciaga logo.',
        category: "Fanny Packs",
        image: "https://asset.cloudinary.com/dmhnsp8sj/a73c12bfd35f9dabf77a8fb4e35cb378",
        occasions: "Casual",
        brand: "Balenciaga",
        color: "Blue",
      },
       {
        id: 3,
        title: "Navy Nylon Bag",
        price: 995,
        descripton: 'Break a sweat with class using this athletic crafted bag featuring the classic logo pattern.',
        category: "Duffel Bags",
        image: "https://asset.cloudinary.com/dmhnsp8sj/786c951ae3e086a4248e741a5a09aec5",
        occasions: "Athleisure",
        brand: "Off-White",
        color: "Dark Blue",
      }
      ],

      Clothing:[
      {
        id: 1,
        title: "Mercantile Mens Classic Fit Oxford",
        price: 80.27,
        descripton: `Maximum comfort and style await with the Oxford shirt's microfibers tailored to suit your needs.`,
        category: "Shirts",
        image: "https://asset.cloudinary.com/dmhnsp8sj/997b940b47c664bbe4d3bb3424e33c08",
        occasions: "Formal", 
        brand: "J.Crew",
        color: "Green",
      },
       {
        id: 2,
        title: "Level T Cotton T-Shirt",
        price: 135.33,
        descripton: 'Crewneck Tee meeting your essential needs, made with premium cotton pullover style.',
        category: "T-Shirts",
        image: "https://asset.cloudinary.com/dmhnsp8sj/1dbf98678028e152a0b6c18da907d3fe",
        occasions: "Casual",
        brand: "Rick Owens",
        color: "Orange",
      },
       {
        id: 3,
        title: "Universal Winter Mens Jacket",
        price: 335.49,
        descripton: 'Arctic tested jacket, perfect for your winter wardrobe.',
        category: "Outerwear",
        image: "https://asset.cloudinary.com/dmhnsp8sj/f026240a8b565a032507442d4aa3f8c6",
        occasions: "Casual",
        brand: "Converse",
        color: "Dark Blue",
      },
      {
        id: 4,
        title: "Oversized Suit Trousers",
        price: 1181,
        descripton: 'Altered to an oversized fit, lunge with ease with this stylish bottom.',
        category: "Trousers",
        image: "https://asset.cloudinary.com/dmhnsp8sj/b1c712c6966b7e8ac2ef38b3bcf5ab01",
        occasions: "Formal", 
        brand: "Off-white",
        color: "Blue",
      },
      {
        id: 5,
        title: "Sportswear Dance Cargo Pants",
        price: 62.99,
        descripton: 'Definitely stand out with these athletic bottoms with a 3D Classic Swoosh',
        category: "Jeans",
        image: "https://asset.cloudinary.com/dmhnsp8sj/88ff50ca1d8ceb99cf8b5303b0d0a172",
        occasions: "Athleisure",
        brand: "Nike",
        color: "Orange",
      },
      {
        id: 6,
        title: "Trefoil Essential Shorts",
        price: 60,
        descripton: 'Easy to wear drawcord waist shorts that promises comfort.',
        category: "Shorts",
        image: "https://asset.cloudinary.com/dmhnsp8sj/65bfb65670de3fc13a6d394a141e721e",
        occasions: "Athleisure",
        brand: "Adidas",
        color: "Green",
      }
      ]

    };
